const express = require('express')
const app = express()
app.use(express.json())
const userRouter = require('./src/modules/Usermodule/router/user_router')
const productRouter = require('./src/modules/productModule/router/product.router')
const categoryRouter = require('.src/modules/CategoryModule/router/category.router')
const reviewRouter = require('.src/modules/ReviewModule/router/review.router')
const adminRouter = require('.src/modules/adminModule/router/admin.router')
const port = process.env.PORT | 5000;
require('./db/mongoose')
app.use(express.json())
app.use(userRouter)
app.use(productRouter)
app.use(categoryRouter)
app.use(reviewRouter)
app.use(adminRouter)
app.get('/',(req,res)=>{
    res.status({message:'Start using app'})
})
app.listen(port,()=>{
    console.log(`Server is running on port + ${port}`)
})